* pandas 底层很多是用Numpy来实现
* Numpy是多维数据（ndarray）的科学计算包
* 数组是相同数据类型按一定顺序排列的组合

# Numpy
 * visual gaide:https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d
 * Vectors 1D array
 * Matrices 2D array
 * 3D and above

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# 1. array objects
https://numpy.org/doc/stable/reference/arrays.html

https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy-array
* object	数组或嵌套的数列
* dtype	数组元素的数据类型，可选
* copy	对象是否需要复制，可选
* order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
* subok	默认返回一个与基类类型一致的数组
* ndmin	指定生成数组的最小维度

In [2]:
print(arr)

[1 2 3 4 5]


In [5]:
# 二维数组
a = np.array([[1,2]
            ,[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [7]:
arr2 = np.array((1,2,3))
arr2

array([1, 2, 3])

In [8]:
arr3 = np.array("123")
arr3

array('123', dtype='<U3')

In [11]:
arr4 = np.array([[1,2,3]
                ,[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

# 2. Numpy array creation routines
https://numpy.org/doc/stable/reference/generated/numpy.arange.html

## 2.1 Arrage range

In [57]:
a = np.arange(1,15,3)
a

array([ 1,  4,  7, 10, 13])

In [14]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2.2 Zeros & Ones & eye & empty

In [20]:
np.zeros(3, dtype = int) # 长度3的vector

array([0, 0, 0])

In [21]:
np.zeros((2,3)) # 2 index 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(3) # 单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty((3,3)) # 空数组， 只占用空间不填充任何值

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2.3 Random sampling
 numpy.random

In [33]:
import numpy as np
# np.random.rand(3) # three 0-1 number
np.random.rand(2,3) 

array([[2.88854716e-02, 5.13338112e-01, 2.21605722e-04],
       [1.05818945e-01, 7.51282788e-01, 3.50982884e-01]])

In [34]:
# normal distribution
np.random.randn(2,3)

array([[-0.16146135,  0.60327246,  0.41886999],
       [ 1.16282718, -2.24427684, -0.05717299]])

In [37]:
# int
np.random.randint(1,5,size = 3) #包含1不含5 [1,5)

array([2, 1, 2])

In [42]:
# [0,5)
np.random.randint(0,5,size = (2,3)) #包含1不含5

array([[3, 4, 4],
       [0, 2, 0]])

In [43]:
# float [0,1)
np.random.random_sample(size =3)

array([0.94459967, 0.92580963, 0.11564943])

In [51]:
# 固定样本
# np.random.choice(a,size = 3, replace = False, p = None)
# a 可以时数组 - 一个样本
# a 可以是正数 - range(a)
for i in range(5):
    print(i)
np.random.choice(5, size = 3)

0
1
2
3
4


array([4, 3, 1])

In [54]:
np.random.choice((1,2,3),size = 10)

array([2, 2, 3, 2, 1, 3, 1, 3, 3, 1])

## 打乱

In [61]:
a = np.arange(1,11)
print(a)
np.random.shuffle(a)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 8  4 10  9  2  7  3  6  1  5]


## 查看数据类型

In [63]:
arr.dtype # 数据类型

dtype('int64')

In [64]:
arr.shape # 形状

(10,)

In [65]:
arr.size # 数据量

10

In [66]:
arr.ndim # 维度

1

# 3. 选取数据
* 索引
* 切片 - 光标


## 3.1 一维数组

In [74]:
arr = np.arange(1,50,3)

In [75]:
arr[0]

1

In [77]:
arr[0:5]

array([ 1,  4,  7, 10, 13])

### bool 筛选

In [80]:
arr>10

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [81]:
arr[arr>10]

array([13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## 3.2 多维数组

In [85]:
arr = np.array([[1,2,3]
                ,[4,5,6]
                ,[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr[0] # index

array([1, 2, 3])

In [93]:
arr[0:2] # 第0行 和 第1行 - slicing

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr[:,0] # columns

array([1, 4, 7])

In [94]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [97]:
# arr[:,0] # first columns
# arr[:,0] > 2 # 第一列大于2的数
arr[arr[:,0]>2]
# 会把队迎行全都晒

array([[4, 5, 6],
       [7, 8, 9]])

In [98]:
# 你就摆烂吧！！！！！！
# 不学习！！！
# 看看你男朋友！多努力呀！～

# 4. 数组 预处理

## 4.1 类型转化
* int
* float
* object
* string_
* unicode_

In [99]:
arr.dtype

dtype('int64')

In [103]:
arr.astype(np.string_).dtype # S21: 长度为21

dtype('S21')

In [105]:
arr_new = arr.astype(np.object)

/var/folders/dq/vyz01f_d6_9554rf0l07d8p00000gn/T/ipykernel_5175/3470983748.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr_new = arr.astype(np.object)


In [106]:
arr_new.dtype

dtype('O')

## 4.2 缺失值处理

In [107]:
arr = np.array([1,2,np.nan,4])
arr

array([ 1.,  2., nan,  4.])

In [108]:
np.isnan(arr)

array([False, False,  True, False])

In [110]:
arr[np.isnan(arr)] # bool索引

array([nan])

In [113]:
arr[np.isnan(arr)] = 0
arr.astype(int)

array([1, 2, 0, 4])

## 4.3重复数据查看

In [115]:
arr = np.array([9,0,1,3,5,1,3,4,5,1,2])
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 9])

## 4.4 数据重塑

### 多维数组

In [118]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [119]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [121]:
arr = np.array([[1,2,3,4]
               ,[5,6,7,8]
               ,[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
arr.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [127]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 转置

In [129]:
arr = np.array([[1,2,3,4]
               ,[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## 4.5 数组合并和拆分

In [151]:
import numpy as np
arr = np.array([[1,2,3]
               ,[4,5,6]])
arr2 = np.array([[1,2,3]
               ,[4,5,6]])

### Horizon

In [138]:
np.concatenate([arr,arr2],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [139]:
np.concatenate([arr,arr2],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [141]:
np.hstack([arr,arr2]) # horizon vertical

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [142]:
np.column_stack([arr,arr2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Vertical

In [144]:
np.concatenate([arr,arr2],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [145]:
np.vstack([arr,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [146]:
np.row_stack([arr,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### 拆分

In [160]:
import numpy as np
arr = np.array([[1,2,3]
               ,[4,5,6]])
arr2 = np.array([[1,2,3]
               ,[4,5,6]])
arr = np.concatenate([arr,arr2],axis = 0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [167]:
np.split(arr,
        [1,3], # 按光标拆分
        axis = 0 # 按行拆分
        )

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [1, 2, 3]]),
 array([[4, 5, 6]])]

In [170]:
np.split(arr,
        [1,3], # 按光标拆分
        axis = 1 # 按行拆分
        )

[array([[1],
        [4],
        [1],
        [4]]),
 array([[2, 3],
        [5, 6],
        [2, 3],
        [5, 6]]),
 array([], shape=(4, 0), dtype=int64)]