# 1. 元素函数
* log, log10, log2, log1p = log(1 + x)
* modf,将小数和整数部分分别以独立数组返回



In [3]:
import numpy as np
arr = np.array([[1,2,3]
               ,[-4,-5,-6]])
np.abs(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
np.sqrt(arr)

/var/folders/dq/vyz01f_d6_9554rf0l07d8p00000gn/T/ipykernel_5764/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[1.        , 1.41421356, 1.73205081],
       [       nan,        nan,        nan]])

In [8]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.83156389e-02, 6.73794700e-03, 2.47875218e-03]])

In [9]:
np.log1p(arr)

/var/folders/dq/vyz01f_d6_9554rf0l07d8p00000gn/T/ipykernel_5764/715331768.py:1: RuntimeWarning: invalid value encountered in log1p
  np.log1p(arr)


array([[0.69314718, 1.09861229, 1.38629436],
       [       nan,        nan,        nan]])

In [10]:
import numpy as np
arr = np.array([[1.1,2.3,3.4]
               ,[-4,-5,-6]])

In [11]:
np.modf(arr)

(array([[ 0.1,  0.3,  0.4],
        [-0. , -0. , -0. ]]),
 array([[ 1.,  2.,  3.],
        [-4., -5., -6.]]))

In [14]:
arr = np.array([[1.1,2.3,3.4]
               ,[np.nan,-5,-6]])
np.isnan(arr)

array([[False, False, False],
       [ True, False, False]])

# 2. 统计函数
axis
* sum mean
* std var
* min max
* argmin argmax : 最小 最大 对应的索引
* cumsum ：累和 return 数组
* cumprod ：累积数组

In [19]:
import numpy as np
arr = np.array([[1,2,3]
               ,[4,9,6]
               ,[7,8,9]])

In [20]:
arr.max()

9

In [21]:
arr.max(axis = 1) # 每一行的最大值

array([3, 9, 9])

In [23]:
arr.max(axis = 0) # 每一列的最大值

array([7, 9, 9])

In [24]:
arr.sum(axis = 1)

array([ 6, 19, 24])

In [28]:
arr.argmin()

0

In [30]:
arr.argmax()

4

In [31]:
arr.cumsum()

array([ 1,  3,  6, 10, 19, 25, 32, 40, 49])

In [33]:
arr.cumprod()

array([     1,      2,      6,     24,    216,   1296,   9072,  72576,
       653184])

# 3. `np.where( )`函数

In [36]:
arr = np.array([56,13,75,84])

In [38]:
np.where(arr>=60,"及格","不及格")

array(['不及格', '不及格', '及格', '及格'], dtype='<U3')

In [40]:
np.where(arr>=60) # 返回索引

(array([2, 3]),)

In [41]:
location = np.where(arr>=60) # 返回索引
location

(array([2, 3]),)

In [42]:
arr[location]

array([75, 84])

# 4. 排序

In [47]:
arr = np.array([56,13,75,84])

In [48]:
np.sort(arr) # 返回一个数组

array([13, 56, 75, 84])

In [49]:
arr

array([56, 13, 75, 84])

In [51]:
arr.sort() # 更改数组元素的顺序
arr

array([13, 56, 75, 84])

# 5. set 关系

In [54]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,3,4,5])

In [59]:
np.in1d(arr1,arr2) # 以第一个数组为基础，第二个数组有的话：True

array([ True, False,  True,  True])

In [60]:
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5])

In [62]:
np.intersect1d(arr1,arr2)

array([1, 3, 4])

In [63]:
np.setdiff1d(arr1,arr2)
# 在1不再2 ： A-AB

array([2])